import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';

const activitiesButtonsStyle = css`
  display: flex;
  margin-top: 20px;
  justify-content: center;
  text-align: center;

  button {
    border-radius: 100px;
    padding: 30px;
    border-width: 5px;
    border-style: solid;
    margin: 50px;
    /* text-align: center; */
    text-transform: uppercase;
    display: inline-block;
    font-size: 15px;
    width: 120px;
    height: 120px;

    cursor: pointer;
  }
  a {
    text-decoration: none;
  }
`;

const artButtonStyle = css`
  text-align: center;
  font-weight: bold;
  color: #fff;
  background-color: #800080;
  margin-right: 30px;
`;
const musicButtonStyle = css`
  font-weight: bold;
  color: #fff;
  background-color: #ab0068;
  margin-right: 30px;
`;
const cookingButtonStyle = css`
  font-weight: bold;
  color: #fff;
  background-color: #e8c954;
  margin-right: 30px;
`;
const danceButtonStyle = css`
  font-weight: bold;
  color: #fff;
  background-color: #008080;
  margin-right: 30px;
`;
const sportButtonStyle = css`
  font-weight: bold;
  color: #fff;
  background-color: #088da5;
`;

export default function Home(props) {
  return (
    <Layout userObject={props.userObject}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src="/hero-1.jpg" width="1600" height="500" />
      <div>
        <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit</h1>
        <h2>
          Quam vulputate dignissim suspendisse in est ante in. Ipsum faucibus
          vitae aliquet nec. Purus sit amet volutpat consequat mauris nunc.
          Volutpat odio facilisis mauris sit amet massa vitae.
        </h2>
        <h3>
          Velit euismod in pellentesque massa placerat duis. Tincidunt vitae
          semper quis lectus nulla at. Eget egestas purus viverra accumsan in
          nisl nisi. Venenatis cras sed felis eget velit aliquet sagittis id
          consectetur. Dui sapien eget mi proin sed libero. Morbi quis commodo
          odio aenean.
        </h3>
      </div>
      <div css={activitiesButtonsStyle}>
        <div>
          <Link href="/">
            <a>
              <button css={artButtonStyle}>Art</button>
            </a>
          </Link>
        </div>
        <div>
          <Link href="/">
            <a>
              <button css={musicButtonStyle}>Music</button>
            </a>
          </Link>
        </div>
        <div>
          <Link href="/">
            <a>
              <button css={cookingButtonStyle}>Cooking</button>
            </a>
          </Link>
        </div>
        <div>
          <Link href="/">
            <a>
              <button css={danceButtonStyle}>Dance</button>
            </a>
          </Link>
        </div>
        <div>
          <Link href="/">
            <a>
              <button css={sportButtonStyle}>Sport</button>
            </a>
          </Link>
        </div>
      </div>
    </Layout>
  );
}
